# -*- coding: utf-8 -*-
"""init_db_only.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1neeTjVnE25UiGlE9EvDYHmZ4pG9Q4Q8y
"""

from pathlib import Path
from sqlalchemy import create_engine

from models import Base


BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / 'recipes.db'


def main() -> None:
    engine = create_engine(f'postgresql:///{DB_PATH}')
    Base.metadata.create_all(engine)
    print(f'Таблицы созданы: {DB_PATH}')


if __name__ == '__main__':
    main()